[build]
  functions = "netlify/functions"

# Optional: Add other configurations as needed
[build.environment]
  NODE_VERSION = "14"

# Optional: Redirects and headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"